services:
  dashboard:
    container_name: stefan-dashboard
    build: .
    ports:
      - "8090:80"
    restart: unless-stopped
    depends_on:
      - dashboard-api
    volumes:
      - ./img:/usr/share/nginx/html/img:ro

  dashboard-api:
    container_name: dashboard-api
    build: ./api
    restart: unless-stopped
    env_file:
      - .env
